export const CREATE_INCIDENT = "CREATE_INCIDENT";
export const RETRIEVE_INCIDENTS = "RETRIEVE_INCIDENTS";
export const UPDATE_INCIDENT = "UPDATE_INCIDENT";
export const DELETE_INCIDENT = "DELETE_INCIDENT";
export const DELETE_ALL_INCIDENTS = "DELETE_ALL_INCIDENTS";